"""Application path and runtime constants for ApiDog."""

from __future__ import annotations

APP_DISPLAY_NAME = "ApiDog"
APP_DATA_FOLDER_NAME = "ApiDog"

ENV_DATA_DIR = "APIDOG_DATA_DIR"
ENV_USE_APPDATA = "APIDOG_USE_APPDATA"
ENV_USE_APPDATA_TRUE = "1"
ENV_DESKTOP_SHELL = "APIDOG_DESKTOP_SHELL"
ENV_DESKTOP_SHELL_TRUE = "1"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 19527
DEFAULT_TIMEOUT_SECONDS = 360
FRONTEND_DEV_PORT = 5173

HEALTH_PATH = "/api/health"
HEALTH_WAIT_ATTEMPTS = 40
HEALTH_WAIT_INTERVAL_SECONDS = 0.25

SINGLE_INSTANCE_MUTEX_NAME = "Local\\ApiDogSingleInstanceMutex"
WIN_ERROR_ALREADY_EXISTS = 183
WIN_MB_ICONERROR = 0x10

WINDOW_WIDTH = 1440
WINDOW_HEIGHT = 900
WINDOW_MIN_WIDTH = 1100
WINDOW_MIN_HEIGHT = 700
